services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: thisismydesign/rails-docker-boilerplate:local
    command: sleep infinity
    ports:
      - 3000:3000
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app

volumes:
  bundle_cache:
